In [1]:
import numpy as np

In [2]:
# Creating an empty array

In [5]:
array_empty = np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Creating an identity matrix in numpy

In [13]:
array_eye = np.eye(10)
array_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
# I want to print the numbers in an array till 20
# Method - arrange(startvalue, stopvalue, stepcount)

In [16]:
x = np.arange(20) # Note: Last value is always exclusive.
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
# req: I want to print the even and odd numbers till 20

In [22]:
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
array_of_odds = np.arange(1,20,2)
array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
# will it accept the float arguments?

In [30]:
array_of_odd_floats = np.arange(0.1,3,0.2)
array_of_odd_floats

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5,
       2.7, 2.9])

In [29]:
# Dimesnions (x,y)
# (x) --- 1d array
# (x,y) --- 2d array
# (x,y,z) ---  3d array

In [31]:
array_2d = np.array([(2,4,6), (3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [32]:
array_2d.shape

(2, 3)

In [33]:
array_2d.ndim

2

In [34]:
# Int question - Shape vs ndim. Shape gives the shape of the dimensions while ndim gives the deimensions information in numbers

In [35]:
# using reshape to create n dimensional arrays

In [38]:
x=np.arange(6) #1 d array
x

array([0, 1, 2, 3, 4, 5])

In [42]:
x = np.arange(6).reshape(3,2) # reshape only works if the value given is equla to multiplication of the value. i.e, 3*2=6
x

array([[0, 1],
       [2, 3],
       [4, 5]])