In [6]:
# Introduction to 3rd party libraries of Python:
# Library: Collection of programs put together is called as Library.
# Library: function.... group of classes.... group of modules.... Libraries

In [5]:
# Intro to Numpy
# Numpy Overview - Numpy stands for numerical python.It is a foundational library to make the AI, ML and DL algorithms to work smoothly. It is also used for scientific computations.

In [7]:
# Installation of Numpy: 

In [8]:
!pip install numpy #excalmatory marks executes the command from the cmd terminal by connecting to the internet.

In [9]:
# Datatypes in Numpy:
# 1 ndarray - N dimensional arrays.

In [10]:
# Req - Create an Array from a regular python list

In [11]:
import numpy as np #------> alias name(np - is the standard followed by the Python orgs)

In [12]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [13]:
type(array_one)

numpy.ndarray

In [14]:
numbers = [5,6,7,8]
array_two = np.array(numbers)
array_two

array([5, 6, 7, 8])

In [15]:
type(array_two)

numpy.ndarray

In [16]:
# Note: Array is very similar ro a list
# Interview question: Given an array and a List to you, what do you choose? and which one will have high performance?
# Ans: Array is highly beneficial - Internal implementation of storing the data is optimised
# and retrieves the data in a faster manner.

In [17]:
# Req: creation of arrays of zeros with desired shape(x,y)
# where x is number of rows and y is number of columns

In [20]:
array_of_zeros = np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# creation of arrays of ones

In [23]:
array_of_ones = np.ones((4,5))
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Note: Internal implementation of an array is float (decimals).

In [26]:
array_of_ones_int = np.ones((4,5), dtype=np.int16) #int16, int32, int64
array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)