In [1]:
import numpy as np

In [2]:
# Arithmetic operations in Numpy

In [3]:
a= np.array([10,10,10])
b = np.array([5,5,5])

In [4]:
a+b

array([15, 15, 15])

In [5]:
a-b

array([5, 5, 5])

In [7]:
a*b

array([50, 50, 50])

In [8]:
a/b

array([2., 2., 2.])

In [10]:
a%3 # Modulous operator, gives out the remainder..

array([1, 1, 1], dtype=int32)

In [ ]:
# COmparision operators

In [11]:
a > 25

array([False, False, False])

In [12]:
a <25

array([ True,  True,  True])

In [13]:
# Modifing an existing array without creating a new one

In [14]:
a

array([10, 10, 10])

In [17]:
a *= 3 # I have multiplied the number with 3
a

array([270, 270, 270])

In [18]:
b+=a # b is holding 5 + a is 270

In [19]:
b

array([275, 275, 275])

In [20]:
# *** Unary operators: 

In [21]:
ages = np.array([12,15,18,20])

In [22]:
# I want to know total sum of the array

In [23]:
ages.sum()

65

In [24]:
# I want to know the minimum value of the array

In [25]:
ages.min() # min value

12

In [26]:
ages.max() # max value

20

In [27]:
ages.mean() # mean value

16.25