In [1]:
# Iterating through Numpy

In [2]:
import numpy as np

In [4]:
# Multi dimenensional array - iteration

In [5]:
students = np.array([['ujwal', 'prakash', 'rishika'], [71,65,36], [100,75,50]])

In [6]:
for i in students:
    print('i=', i)

i= ['ujwal' 'prakash' 'rishika']
i= ['71' '65' '36']
i= ['100' '75' '50']


In [7]:
# Flatte function - row based iteration

In [9]:
for x in students.flatten():
    print (x)

ujwal
prakash
rishika
71
65
36
100
75
50


In [10]:
# Forton order - Column wise iteration

In [11]:
for x in students.flatten(order = 'F'):
    print (x)

ujwal
71
100
prakash
65
75
rishika
36
50


In [12]:
x = np.arange(12).reshape(3,4)

In [13]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
# nditer
for i in np.nditer(x): #row wise iteration
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11


In [19]:
for i in np.nditer(x, order = ''): # column wise iteration
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
